# Generated by Django 5.1.4 on 2024-12-24 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orientacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(default='', max_length=300)),
                ('atividade_foiFeita', models.BooleanField(default=False)),
                ('prazo', models.DateField()),
                ('fk_Orientacao_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientacao.orientacao')),
            ],
        ),
    ]
