# Generated by Django 5.1.4 on 2024-12-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='atividade_foiFeita',
            new_name='foiFeita',
        ),
    ]
