# Generated by Django 5.1.4 on 2024-12-24 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orientacao',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('fk_Usuario_ID_Aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientacao_aluno', to='usuario.usuario')),
                ('fk_Usuario_ID_Professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientacao_professor', to='usuario.usuario')),
            ],
        ),
    ]
