# Generated by Django 5.1.4 on 2025-01-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orientacao', '0003_orientacao_foisolicitada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orientacao',
            name='solicitacaoRecusada',
        ),
    ]
