# Generated by Django 5.1.4 on 2024-12-24 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orientacao', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('caminho_arquivo', models.CharField(max_length=100)),
                ('data_publicacao', models.DateField(auto_now_add=True)),
                ('horario_publicacao', models.CharField(max_length=10)),
                ('ID_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
                ('fk_Orientacao_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientacao.orientacao')),
            ],
        ),
    ]
