# Generated by Django 5.1.4 on 2025-01-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_caminho_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caminho_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
