# Generated by Django 5.1.4 on 2024-12-24 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orientacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45)),
                ('data_agendada', models.DateField(auto_now_add=True)),
                ('horario_agendado', models.CharField(max_length=10)),
                ('justificativa', models.CharField(max_length=100)),
                ('foiJustificada', models.BooleanField(default=False)),
                ('foiFeita', models.BooleanField(default=False)),
                ('fk_Orientacao_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientacao.orientacao')),
            ],
        ),
    ]
