# Generated by Django 5.1.4 on 2024-12-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='horario_agendado',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
