# Generated by Django 5.1.4 on 2024-12-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0002_alter_reuniao_horario_agendado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='justificativa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
