# Generated by Django 5.1.4 on 2025-01-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniao', '0003_alter_reuniao_justificativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='data_agendada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='horario_agendado',
            field=models.TimeField(),
        ),
    ]
