# Generated by Django 5.1.4 on 2024-12-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area_interesse', '0002_rename_area_interesse_id_areainteresse_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=150)),
                ('email', models.CharField(default='', max_length=150)),
                ('usuario', models.CharField(default='', max_length=50)),
                ('senha', models.CharField(default='', max_length=150)),
                ('matricula', models.CharField(default='', max_length=20)),
                ('Usuario_TIPO', models.IntegerField()),
                ('area_interesse', models.ManyToManyField(to='area_interesse.areainteresse')),
            ],
        ),
    ]
