# Generated by Django 5.1.4 on 2024-12-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_interesse', '0002_rename_area_interesse_id_areainteresse_id_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuario', '0002_usuario_groups_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='area_interesse',
            field=models.ManyToManyField(blank=True, to='area_interesse.areainteresse'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuario_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuario_permissions', to='auth.permission'),
        ),
    ]
