# Generated by Django 5.1.4 on 2024-12-26 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_area_interesse_alter_usuario_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
