# Generated by Django 5.1.4 on 2024-12-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_usuario_senha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ID',
            new_name='id',
        ),
    ]
