# Generated by Django 5.1.4 on 2024-12-26 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_rename_id_usuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario',
            new_name='username',
        ),
    ]
