# Generated by Django 5.1.4 on 2024-12-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_interesse', '0002_rename_area_interesse_id_areainteresse_id_and_more'),
        ('usuario', '0006_rename_usuario_usuario_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id',
            new_name='ID',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='area_interesse',
            field=models.ManyToManyField(to='area_interesse.areainteresse'),
        ),
    ]
