# Generated by Django 5.1.4 on 2024-12-26 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_rename_id_usuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ID',
            new_name='id',
        ),
    ]
