# Generated by Django 5.1.4 on 2024-12-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_interesse', '0002_rename_area_interesse_id_areainteresse_id_and_more'),
        ('usuario', '0010_rename_id_usuario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id',
            new_name='ID',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='', editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Usuario_TIPO',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='area_interesse',
            field=models.ManyToManyField(to='area_interesse.areainteresse'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
