# Generated by Django 5.1.4 on 2024-12-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_interesse', '0002_rename_area_interesse_id_areainteresse_id_and_more'),
        ('usuario', '0013_remove_usuario_area_interesse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='area_interesse',
            field=models.ManyToManyField(to='area_interesse.areainteresse'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Usuario_TIPO',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='', max_length=150),
        ),
    ]
