# Generated by Django 5.1.4 on 2024-12-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_alter_usuario_email_alter_usuario_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
