# Generated by Django 5.1.4 on 2024-12-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0019_usuario_groups_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Usuario_TIPO',
            field=models.IntegerField(default=0),
        ),
    ]
