# Generated by Django 5.1.4 on 2024-12-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0020_alter_usuario_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
