# Generated by Django 5.1.4 on 2025-01-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0021_alter_usuario_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='quantidade_orientandos',
            field=models.IntegerField(default=0),
        ),
    ]
