# Generated by Django 5.1.4 on 2025-01-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0022_usuario_quantidade_orientandos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tema',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
